version: '3.7'
services:
    discovery-server:
        container_name: discovery-server
        build:
            context: discovery-server
            dockerfile: Dockerfile
        image: discovery-server:latest
        ports:
            - 8761:8761