version: "3.7"

services:
  tennis-player-db:
    container_name: tennis-player-db
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: tennis_player_db
